manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Rirdical
      url-base: https://github.com/Rirdical
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-nice-oled
      remote: Rirdical
      revision: 717bbae7
  self:
    path: config
